#osgi.configuration.cascaded=true
#osgi.sharedConfiguration.area=file:c:/frontrunnerv3/runtime/common/configuration
osgi.console.enable.builtin=true
osgi.console.useConfigAdmin=false
osgi.console=
osgi.noShutdown=true

org.osgi.framework.executionenvironment=J2SE-1.2,J2SE-1.3,J2SE-1.4,J2SE-1.5,JRE-1.1,JavaSE-1.6,OSGi/Minimum-1.0,OSGi/Minimum-1.1,OSGi/Minimum-1.2
#osgi.java.profile=JavaSE-1.6.profile
# if osgi.java.profile was being loaded, we would need to define these packages.. see defect:xxxxx
# Note despite javax.comm is not used by admin application, it's a dependency on the omslibrary jar.
org.osgi.framework.system.packages=javax.comm,\
jssc,\
de.entropia.can,\
org.ietf.jgss,\
javax.crypto,\
javax.crypto.spec,\
javax.security.sasl,\
javax.crypto.interfaces,\
javax.security.auth,\
javax.security.auth.login,\
javax.activation,\
javax.management,\
javax.management.modelmbean,\
javax.management.remote,\
javax.management.remote.rmi,\
javax.swing,\
javax.swing.border,\
javax.swing.colorchooser,\
javax.swing.event,\
javax.swing.filechooser,\
javax.swing.plaf,\
javax.swing.plaf.basic,\
javax.swing.plaf.metal,\
javax.swing.plaf.multi,\
javax.swing.plaf.synth,\
javax.swing.table,\
javax.swing.text,\
javax.swing.text.html,\
javax.swing.text.html.parser,\
javax.swing.text.rtf,\
javax.swing.tree,\
javax.swing.undo,\
javax.security.cert,\
javax.xml.parsers,\
javax.xml.bind,\
javax.xml.xpath,\
javax.net.ssl,\
sun.swing,\
org.w3c.dom,\
org.w3c.dom.bootstrap,\
org.w3c.dom.events,\
org.w3c.dom.ls,\
org.xml.sax.ext,\
org.xml.sax.helpers,\
org.xml.sax,\
javax.sql,\
javax.net,\
javax.xml.datatype,\
javax.xml.namespace,\
javax.xml.stream,\
javax.xml.transform,\
javax.xml.transform.dom,\
javax.xml.transform.stax,\
javax.xml.transform.sax,\
javax.xml.transform.stream,\
javax.xml.validation,\
javax.xml.ws.spi.http,\
javax.naming,\
javax.naming.directory,\
javax.naming.spi,\
javax.security.auth.callback,\
javax.security.auth.x500,\
javax.accessibility,\
sun.misc,\
javax.tools,\
javax.lang.model.element,\
javax.naming.ldap,\
org.jdom,\
org.jdom.input,\
org.jdom.output,\
io.netty.channel,\
org.slf4j,\
com.jcraft.jsch,\
net.sf.expectit,\
net.sf.expectit.matcher,\
javax.script,\
com.profesorfalken.jpowershell,\
com.networknt.schema,\
com.fasterxml.jackson.datatype.jsr310,\
javax.validation.constraints,\
io.vertx.ext.web.impl,\
com.google.crypto.tink.subtle,\
net.jcip.annotations,\
org.apache.commons.csv,\
com.sun.javafx

osgi.bundles=\
reference:file:../../bundles/org.eclipse.osgi.services-3.5.100@2:start,\
reference:file:../../bundles/org.eclipse.equinox.ds-1.4.400.jar@2:start,\
reference:file:../../bundles/org.eclipse.equinox.util-1.0.500.jar@2:start,\
reference:file:../../bundles/org.eclipse.equinox.console-1.1.200.jar@2:start,\
reference:file:../../bundles/org.eclipse.equinox.console.ssh-1.0.100.jar@2:start,\
reference:file:../../bundles/org.eclipse.equinox.console.jaas.fragment-1.0.0.jar,\
reference:file:../../bundles/mina-core-2.0.7.jar@2:start,\
reference:file:../../bundles/sshd-core-0.14.0.jar@2:start,\
reference:file:../../bundles/mail-1.4.3.jar@2:start,\
reference:file:../../bundles/xz-1.8@2:start,\
reference:file:../../bundles/commons-compress-1.20@2:start,\
reference:file:../../bundles/commons-net-3.2@2:start,\
reference:file:../../bundles/commons-lang3-3.9.jar@2:start,\
reference:file:../../bundles/commons-text-1.8.jar@2:start,\
reference:file:../../bundles/commons-io-1.4.jar@2:start,\
reference:file:../../bundles/slf4j-api-1.7.25@2:start,\
reference:file:../../bundles/jts-core-1.16.1.1-mms.jar,\
reference:file:../../bundles/jackson-core-2.11.4.jar@2:start,\
reference:file:../../bundles/jackson-annotations-2.11.4.jar@2:start,\
reference:file:../../bundles/jackson-databind-2.11.4.jar@2:start,\
reference:file:../../bundles/jackson-dataformat-yaml-2.11.4.jar@2:start,\
reference:file:../../bundles/jackson-datatype-jsr310-2.10.0.jar,\
reference:file:../../bundles/logback-core-1.2.3.jar@2:start,\
reference:file:../../bundles/logback-classic-1.2.3.jar@2:start,\
reference:file:../../bundles/org.apache.felix.configadmin-1.8.14.jar@2:start,\
reference:file:../../bundles/org.apache.felix.gogo.command-0.10.0.jar@2:start,\
reference:file:../../bundles/org.apache.felix.gogo.runtime-0.10.0.jar@2:start,\
reference:file:../../bundles/org.apache.felix.gogo.shell-0.10.0.jar@2:start,\
reference:file:../../bundles/mariadb-java-client-3.0.11.1-mms.jar@2:start,\
reference:file:../../bundles/snakeyaml-1.33.jar,\
reference:file:../../bundles/mms-extension-logback-1.7.0-076.jar,\
reference:file:../../bundles/omslibrary-1.0.0.47-rev9.jar@3:start,\
reference:file:../../bundles/mms-framework-core-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-tool-jmx-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-driver-dgh-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-driver-can-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-driver-gps-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-framework-geometry-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-framework-gui-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-framework-app-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-simulation-gps-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-simulation-gpsgs-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-adapter-dispatch-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-adapter-webapi-1.7.0-076.jar@3:start,\
reference:file:../../bundles/fcpcommon-1.2.0.22-AHS-15.jar@3:start,\
reference:file:../../bundles/fcpclient-1.2.0.22-AHS-15.jar@3:start,\
reference:file:../../bundles/mms-frontrunner-canvas-3.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-frontrunner-common-3.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-frontrunner-database-3.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-frontrunner-central-3.7.0-076.jar@3:start,\
reference:file:../../bundles/com.diffplug.osgi.extension.sun.misc-0.0.0.jar,\
reference:file:../../bundles/log4j-1.2.17.jar,\
reference:file:../../bundles/log4j-api-2.5.jar,\
reference:file:../../bundles/json-schema-validator-1.0.28.jar,\
reference:file:../../bundles/netty-buffer-4.1.72.Final.jar,\
reference:file:../../bundles/netty-codec-4.1.72.Final.jar,\
reference:file:../../bundles/netty-codec-dns-4.1.72.Final.jar,\
reference:file:../../bundles/netty-codec-http-4.1.72.Final.jar,\
reference:file:../../bundles/netty-codec-http2-4.1.72.Final.jar,\
reference:file:../../bundles/netty-codec-socks-4.1.72.Final.jar,\
reference:file:../../bundles/netty-common-4.1.72.Final.jar,\
reference:file:../../bundles/netty-handler-4.1.72.Final.jar,\
reference:file:../../bundles/netty-handler-proxy-4.1.72.Final.jar,\
reference:file:../../bundles/netty-resolver-4.1.72.Final.jar,\
reference:file:../../bundles/netty-resolver-dns-4.1.72.Final.jar,\
reference:file:../../bundles/netty-transport-4.1.72.Final.jar,\
reference:file:../../bundles/vertx-core-3.9.12.jar,\
reference:file:../../bundles/vertx-codegen-3.9.12.jar,\
reference:file:../../bundles/vertx-auth-common-3.9.12.jar,\
reference:file:../../bundles/vertx-bridge-common-3.9.12.jar,\
reference:file:../../bundles/vertx-jwt-3.9.12.jar,\
reference:file:../../bundles/vertx-web-api-contract-3.9.12-mms-3.jar,\
reference:file:../../bundles/vertx-web-3.9.12-mms-3.jar,\
reference:file:../../bundles/vertx-web-common-3.9.12-mms-3.jar,\
reference:file:../../bundles/nimbus-jose-jwt-9.7.jar,\
reference:file:../../bundles/tink-1.5.0.jar,\
reference:file:../../bundles/jcip-annotations-1.0-1.jar,\
reference:file:../../bundles/swagger-core-2.1.0.jar,\
reference:file:../../bundles/swagger-annotations-2.1.0.jar,\
reference:file:../../bundles/swagger-models-2.1.0.jar,\
reference:file:../../bundles/swagger-parser-core-2.0.16-mms.jar,\
reference:file:../../bundles/swagger-parser-v3-2.0.16-mms.jar,\
reference:file:../../bundles/swagger-parser-project-2.0.16-mms.jar,\
reference:file:../../bundles/mms-frontrunner-server-3.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-frontrunner-server-remote-3.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-frontrunner-server-tools-3.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-tool-i18n-1.7.0-076.jar@3:start,\
reference:file:../../bundles/org.apache.servicemix.bundles.snmp4j-2.2.2_1.jar@3:start,\
reference:file:../../bundles/validation-api-1.1.0.Final.jar,\
reference:file:../../bundles/jaxb-api-2.3.0.jar,\
reference:file:../../bundles/guava-27.0.1-jre.jar,\
reference:file:../../bundles/failureaccess-1.0.1.jar,\
reference:file:../../bundles/protobuf-java-3.21.5.jar,\
reference:file:../../bundles/commons-math3-3.6.jar,\
reference:file:../../bundles/netty-tcnative-classes-2.0.46.Final.jar,\
reference:file:../../bundles/commons-csv-1.9.0.jar,\

osgi.bundles.defaultStartLevel=4
#osgi.debug=file:../conf/.options
