#
# Main switch to turn Dispatch Integration on or off.
#
dispatch.integration.enabled=true

#
# Time between pooling of DISPATCH database
#
dispatch.integration.poolingTime=5

#
# Heading angle adjust to DISPATCH. The angle will be multiplied by
# this value, i.e. if set as 10, then 90 degrees will be sent as 900.
#
# According to GPS-PATH RPC definition:
# heading = compass heading 1/10ths deg: N=0, E=900, S=1800, W=2700
#
dispatch.integration.equipmentHeadingAdjust=1

#
# Units
#
enum.unit.star = *
enum.unit.Truck = Truck
enum.unit.SHovel = Shovel
enum.unit.DUmp = Dump
enum.unit.CRusher = Crusher
enum.unit.STockpile = Stockpile
enum.unit.Blast = Blast
enum.unit.WOrkshop = Shop
enum.unit.SHIFtchange = Parkup
enum.unit.CAllPoint = Node
enum.unit.PIt = Pit
enum.unit.REgion = Area
enum.unit.DRill = Drill
enum.unit.DOzer = Dozer
enum.unit.GRAder = Grader
# Aux Crusher: for FRAZPG Hopper Unit
#enum.unit.Hopper = Aux Crusher
#enum.unit.FuelBay = Aux Fuel Bay
# Crusher Panel: for FRPIY Hopper Unit
#enum.unit.Hopper = Crusher Panel
#enum.unit.FuelBay = Fuel Bay Panel
#enum.unit.WDozer = Wheel Dozer
#enum.unit.ACrush = Chancador
#enum.unit.Foreman = Foreman
#enum.unit.WTruck = Aljibe
#enum.unit.Util = Vehiculo Aux 
#enum.unit.Bus = Bus
##   Client specific addons below this point
#enum.unit.Spreader Spreader
#enum.unit.Retro Retro
#enum.unit.Frontal = Frontal Aux 
##  Unkown
#enum.unit.Backhoe = Backhoe
