#######################################
#######################################
# AZPG CONFIGURATION
#######################################
#######################################
# Enable/Disable auto starting GPS Simulation.
simulation.gps.autostart.enabled=false
#This point represents an origin in between the map boundaries 
wgs.origin.latitude=380585718
wgs.origin.longitude=-1324664518
wgs.origin.altitude=1001740
########
# Antenna configuration description:
#
#
# Antenna config for cylinder configuration.
#
#    Format:
#       ANTnum(cylinder): angle, radius, z
#           angle, radius, z in local cylinder coordination of loader.
#           origin is center of rotation of shovel/backhoe.
#           work for FEL as well, but should not use this coordination for FEL.
#              angle : angle of line of rotation of center and antenna position.
#                      counter clockwise from heading direction.
#                      16 bits circular angle.
#             radius : distance from rotation of center.
#                      millimeter
#                  z : height of antenna from ground level.
#                      millimeter
#


# Antenna config for grid configuration.
#
#    Format:
#       ANTnum(grid): x, y, z
#           x, y, z in local grid coordination of loader.
#             x axis is + to heading direction of loader.
#             y axis is + to left hand side of loader.
#             origin of x, y is center of rotation of shovel / backhoe, or articulate point of FEL.
#


S1.antenna.type=cylinder
S1.antenna1.radius=10000
S1.antenna1.offsetAngleDegree=120.0
S1.antenna1.height=5000
S1.antenna2.radius=10000
S1.antenna2.offsetAngleDegree=-120.0
S1.antenna2.height=5000

S2.antenna.type=cylinder
S2.antenna1.radius=10000
S2.antenna1.offsetAngleDegree=120.0
S2.antenna1.height=5000
S2.antenna2.radius=10000
S2.antenna2.offsetAngleDegree=-120.0
S2.antenna2.height=5000


BACK1.antenna.type=cylinder
BACK1.antenna1.radius=10000
BACK1.antenna1.offsetAngleDegree=120.0
BACK1.antenna1.height=5000
BACK1.antenna2.radius=10000
BACK1.antenna2.offsetAngleDegree=-120.0
BACK1.antenna2.height=5000

BACK2.antenna.type=cylinder
BACK2.antenna1.radius=10000
BACK2.antenna1.offsetAngleDegree=120.0
BACK2.antenna1.height=5000
BACK2.antenna2.radius=10000
BACK2.antenna2.offsetAngleDegree=-120.0
BACK2.antenna2.height=5000
FEL.antenna.type=grid
FEL.antenna1.gridX=-5000
FEL.antenna1.gridY=8660
FEL.antenna1.gridZ=5000
FEL.antenna2.gridX=-5000
FEL.antenna2.gridY=-8660
FEL.antenna2.gridZ=5000
EMV1.antenna.height=2000
