#### Configuration for message broker timeouts
messaging.timeout.DistributedCacheReconcileRequest=30000
messaging.timeout.ActivityPathTipAreaRequest=65000
messaging.timeout.ActivityPathLoadSpotRequest=65000
messaging.timeout.ActivityPathDozerSpotRequest=65000
messaging.timeout.ActivityPathRecoveryRequest=65000
messaging.timeout.ActivityPathRecoveryAcceptRequest=20000
messaging.timeout.MixedLocationChangeTypeRequest = 10000
messaging.timeout.TipAreaRemoveRequest = 10000
messaging.timeout.DumpNodesCreateRequest=20000
messaging.timeout.ConvertToAssignCourseRequest=20000
messaging.timeout.SurveyCreateRoadRequest=20000
messaging.timeout.SurveyCreateLocationRequest=20000
messaging.timeout.LocalAreaSpeedLimitCreatePreviewRequest=60000
messaging.timeout.LocalAreaSpeedLimitAddRequest=60000
messaging.timeout.LocalAreaSpeedLimitEditConfigRequest=60000
messaging.timeout.LocalAreaSpeedLimitRemoveRequest=60000
messaging.timeout.RemoteSmnMapDataRequest=15000
messaging.timeout.LocalSmnMapDataRequest=10000
messaging.timeout.EditSplineCourseRequest=60000
messaging.timeout.LocalEmergencyStopRequest=1000
messaging.timeout.LocalEngineOffRequest=1000
messaging.timeout.LocalMotionStopRequest=1000
messaging.timeout.LocalSuspendRequest=1000
messaging.timeout.CreateOrEditDrawnCourseRequest=20000

#### Replicator timeout configuration for replicas.
#### courses
replicator.send.timeout.10200=500
#### road_travel
replicator.send.timeout.11000=500
#### switching_travel
replicator.send.timeout.11100=500
#### spot_travel
replicator.send.timeout.11200=500
#### departure_travel
replicator.send.timeout.11300=500
#### detour_travel
replicator.send.timeout.11400=500
#### pit_loc_info
replicator.send.timeout.12400=500
#### passing_area
replicator.send.timeout.13000=500


## Deny sending full replicas of the following ids:
# FULL ReplicaUpdate is denied for all replicas as default.
# replicator.deny.full.replicas=7000,7200,7400,10200,11000,11100,11200,11300,11400


#***************************************************************************************************
#* Dependencies of Replicable data
#*
#* Declare all dependencies of Replicable data.
#*   FORMAT:
#*       network.cache.list.dependencies.(Replica-ID)=(List of all referred Replica-ID's)
#*
#* Dependencies are used only to build PARTIAL-CACHE in FrontRunner Server.
#* Theese are not used in any other FrontRunner applications, i.e. MineMobile, Controller, Playback and so on.
#*
#* If a Replica of the client which requests PARTIAL-CACHE-DOWNLOAD is already up-to-date,
#* it will be removed from PARTIAL-CACHE even if dependency is declared.
#* So, it won't cause unnecessarily too big PARTIAL-CACHE even if all dependents are declared here.
#* It may fail to reconcile PARTIAL-CACHE in case of missing dependencies,
#* and reconcile failure causes FULL-CACHE download.
#*
#* On the other hand, unnecessary dependents will have size of PARTIAL-CACHE bigger
#* in case they are OUTDATED when creating PARTIAL-CACHE for non-related Replica.
#*
#* Thus, all dependencies need to be declared correctly here.
#***************************************************************************************************
#### TruckDynamicsTable(2000) -> LinearGraph and all inherited dependencies
network.cache.list.dependencies.2000=2

#### Aht$AhtProfile(2100) -> TruckDynamicsTable  and all inherited dependencies
network.cache.list.dependencies.2100=2,2000

#### Awt$AwtProfile(2900) -> TruckDynamicsTable  and all inherited dependencies
network.cache.list.dependencies.2900=2,2000

#### Aht(3000) -> Aht$AhtProfile and all inherited dependencies
network.cache.list.dependencies.3000=2,2000,2100

#### Backhoe(3100) -> Backhoe$BackhoeProfile
network.cache.list.dependencies.3100=2200

#### Dozer(3200) -> Dozer$DozerProfile
network.cache.list.dependencies.3200=2300

#### FrontEndLoader(3300) -> FrontEndLoader$FrontEndLoaderProfile
network.cache.list.dependencies.3300=2400

#### Grader(3400) -> Grader$GraderProfile
network.cache.list.dependencies.3400=2500

#### Hopper(3550) -> Hopper$Bay
network.cache.list.dependencies.3550=3500

#### LightVehicle(3600) -> LightVehicle$LightVehicleProfile
network.cache.list.dependencies.3600=2600

#### Shovel(3700) -> Shovel$ShovelProfile
network.cache.list.dependencies.3700=2700

#### Mht(3900) -> Mht$MhtProfile
network.cache.list.dependencies.3900=2800

#### Awt(4000) -> Awt$AwtProfile
network.cache.list.dependencies.4000=2,2000,2900

#### MixedLocation(9000) -> LocationSurvey
network.cache.list.dependencies.9000=7000

#### IntersectionLocation(9100) -> LocationSurvey
network.cache.list.dependencies.9100=7000

#### TiedownLocation(9200) -> LocationSurvey
network.cache.list.dependencies.9200=7000

#### CrushLocation(9300) -> LocationSurvey and DumpingTypeProfile
network.cache.list.dependencies.9300=7000,8000

#### DefaultCrushLocationConfig(9600) -> DumpingTypeProfile : LocationSurvey will be always NULL.
network.cache.list.dependencies.9600=8000

#### PolylineCourse(10200) -> JointPoint, SplineCourse, SplineLineData
network.cache.list.dependencies.10200=10500,10250,10100

#### SplineCourse(10250) -> SplineLineData, JointPoint, PolylineCourse
network.cache.list.dependencies.10250=10100,10500,10200

#### JointPoint(10500) -> SplineCourse, SplineLineData, PolylineCourse
network.cache.list.dependencies.10500=10250,10100,10200

#### Road Travel(11000)
####     -> All types of Courses (PolylineCourse,SplineCourse) and all inherited dependencies
####     -> All types of Location and all inherited dependencies
####     -> RoadSurvey
network.cache.list.dependencies.11000=7000,7200,8000,9000,9100,9200,9300,10100,10200,10250,10500

#### Switching Travel(11100)
####    -> Aht and all inherited dependencies (through the superclass)
####    -> Road Travel and all inherited dependencies (Dependency on IntersectionLocation is contained in this dependency)
network.cache.list.dependencies.11100=2,2000,2100,2900,3000,4000,7000,7200,8000,9000,9100,9200,9300,10100,10200,10250,11000,10500

#### Spot Travel(11200)
####     -> All types of Courses (PolylineCourse,SplineCourse) and all inherited dependencies
####     -> Road Travel and all inherited dependencies (Dependency on the Location of this spot travel is contained in this dependency)
network.cache.list.dependencies.11200=2,2000,2100,2900,3000,4000,7000,7200,8000,9000,9100,9200,9300,10100,10200,10250,11000,10500

#### Detour Travel(11300) -> Travel(Road Travel,Switching Travel) and all inherited dependencies
network.cache.list.dependencies.11300=2,2000,2100,2900,3000,4000,7000,7200,8000,9000,9100,9200,9300,10100,10200,10250,11000,11100,10500

#### Departure Travel(11400)
####     -> All types of Courses (PolylineCourse,SplineCourse) and all inherited dependencies
####     -> Road Travel and all inherited dependencies (Dependency on the Location of this spot travel is contained in this dependency)
network.cache.list.dependencies.11400=2,2000,2100,2900,3000,4000,7000,7200,8000,9000,9100,9200,9300,10100,10200,10250,11000,10500

#### Tip Area(12000) -> MixedLocation, LocationSurvey and all inherited dependencies
network.cache.list.dependencies.12000=7000, 9000

#### Location Info(12400) : This has too many dependencies.
####     -> All types of Locations and all inherited dependencies
####     -> LoadInfo : All types of Loaders, SpotTravel, DepartureTravel and all inherited dependencies
####     -> DumpInfo : Dozer, LightVehicle, Aht, SpotTravel, DepartureTravel and all inherited dependencies
####     -> CrushInfo : Hopper and all inherited dependencies
####     -> TiedownInfo : FuelBaySystem and all inherited dependencies
####
#### Consider to split into 4, i.e. LoadInfo, DumpInfo, CrushInfo, TiedownInfo.
#### It may be still OK to combine LoadInfo+DumpInfo since they are both for MixedLocation.
network.cache.list.dependencies.12400=2,2000,2100,2200,2300,2400,2600,2700,2900,3000,3100,3200,3300,3500,3550,3600,3700,3800,4000,7000,7200,8000,9000,9100,9200,9300,10100,10200,10250,11000,11200,11400,10500

#### PassingArea(13000) -> Equipment other than Hopper and all inherited dependencies.
network.cache.list.dependencies.13000=2,2000,2100,2200,2300,2400,2500,2600,2700,2800,2900,3000,3100,3200,3300,3400,3500,3700,3800,3900,4000

#### CrusherBayInfo(15000) -> LocationInfo and all inherited dependencies
####    CrusherBayInfo itself is related to CrushInfo and CrushLocation in LocationInfo only.
####    However, it may fail to reconcile LocationInfo if only download the contents of CrushInfo and CrushLocation.
####    All dependencies in LocationInfo needs to be inherited.
network.cache.list.dependencies.15000=2,2000,2100,2200,2300,2400,2600,2700,2900,3000,3100,3200,3300,3500,3550,3600,3700,3800,4000,7000,7200,8000,9000,9100,9200,9300,10100,10200,10250,11000,11200,11400,12400,10500

#### DumpNodeDisplayInfo(19300) -> TipArea and all inherited dependencies
network.cache.list.dependencies.19300=7000,9000,12000

#### IsolationArea(20000) -> All types of Vehicle and all inherited dependencies.  No need Hopper / FuelBaySystem
network.cache.list.dependencies.20000=2,2000,2100,2200,2300,2400,2500,2600,2700,2800,2900,3000,3100,3200,3300,3400,3500,3700,3900,4000

#### ParkArea(20100) -> All types of Vehicle and all inherited dependencies.  No need Hopper / FuelBaySystem
network.cache.list.dependencies.20100=2,2000,2100,2200,2300,2400,2500,2600,2700,2800,2900,3000,3100,3200,3300,3400,3500,3700,3900,4000

#### SmnMaskArea(23000) -> All types of Vehicle and all inherited dependencies.  No need Hopper / FuelBaySystem
####    Unsure why, but SmnMaskArea has Vehicle.
network.cache.list.dependencies.23000=2,2000,2100,2200,2300,2400,2500,2600,2700,2800,2900,3000,3100,3200,3300,3400,3500,3700,3900,4000

#### TurnSignalTravelConfiguration(25100) -> RoadTravel and all inherited dependencies
network.cache.list.dependencies.25100=7000, 7200, 8000, 9000, 9100, 9200, 9300, 10100, 10200, 10250, 11000,10500

#### ReplicableEnbugOuterElement(32766) -> ReplicableEnbugInnerElement
network.cache.list.dependencies.32766=32765
#### ReplicableEnbugElementContainer(32767) -> ReplicableEnbugInnerElement, ReplicableEnbugOuterElement
network.cache.list.dependencies.32767=32765, 32766
#### FrontRunnerEmbeddedConfiguration -> In case hardware clock update fails, retry updating it
frontrunner.hwclock.update.retry=0
