#
# Connection setup
#
Connection.HostName=localhost
Connection.HostPort=3005
#Connection.BackupHostName=localhost
#Connection.BackupHostPort=3006
Connection.DefaultTimeout=100000
Connection.MaxRetires=2
Connection.RetriesTimeout=1000
Connection.FCPReplyTimeout=5000

#
# Log
# Valid levels are: ALL, CONFIG, FINE, FINER, FINEST, INFO, OFF, SEVERE or WARNING.
#
Log.FileName=../logs/FR.FcpClient-%g.log
Log.Level=OFF

#
# FCP version
#
Protocol.MajorVersion=1
Protocol.MinorVersion=0
Protocol.Encoding=1
