# One of TRUE or FALSE. Default is "TRUE". 
logger.enabled=TRUE

# One of SILENT, INFO, FINE or FINEST. Default is "INFO".
logger.log.level=SILENT

# One of FILE, CONSOLE or FILE_AND_CONSOLE. Default is FILE.
logger.handler=FILE

# Absolute path of log file location. Default is "grinchLoggger.log" in current directory.
logger.logFileLocation=../logs/omslibrary.log

# Positive number, denoting size in KB so for 1 mb put 1024. Default is 1024 (1 MB), and maximum is 10240 (1024*10). so if you specify greater than 10240 then 
# it will default back to 1024. 
logger.maxFileSize=10240

# Total number of log files allowed to create in a given directory. Default is 10.
# In case, there is need to create more files than this threshold (due to size overflow), the oldest file is automatically deleted and
# then latest file is backed up and new file created. so there will be always be less or equal to "logger.maxNumberOfFiles" number of log files. Max value you can give here is
# 100. if you give more than that, it will default back to 10.
logger.maxNumberOfFiles=10
