#osgi.configuration.cascaded=true
#osgi.sharedConfiguration.area=file:c:/frontrunnerv3/runtime/common/configuration
osgi.console.enable.builtin=false
osgi.console.useConfigAdmin=false
osgi.console=
osgi.noShutdown=true

org.osgi.framework.executionenvironment=J2SE-1.2,J2SE-1.3,J2SE-1.4,J2SE-1.5,JRE-1.1,JavaSE-1.6,OSGi/Minimum-1.0,OSGi/Minimum-1.1,OSGi/Minimum-1.2
#osgi.java.profile=JavaSE-1.6.profile
# if osgi.java.profile was being loaded, we would need to define these packages.. see defect:xxxxx
# Note despite javax.comm is not used by controller application, it's a dependency on the omslibrary jar.
org.osgi.framework.system.packages=javax.comm,\
jssc,\
de.entropia.can,\
org.ietf.jgss,\
javax.crypto,\
javax.crypto.spec,\
javax.security.sasl,\
javax.crypto.interfaces,\
javax.security.auth,\
javax.security.auth.login,\
javax.security.auth.spi,\
javax.activation,\
javax.management,\
javax.management.modelmbean,\
javax.management.remote,\
javax.management.remote.rmi,\
javax.swing,\
javax.swing.border,\
javax.swing.colorchooser,\
javax.swing.event,\
javax.swing.filechooser,\
javax.swing.plaf,\
javax.swing.plaf.basic,\
javax.swing.plaf.metal,\
javax.swing.plaf.multi,\
javax.swing.plaf.synth,\
javax.swing.table,\
javax.swing.text,\
javax.swing.text.html,\
javax.swing.text.html.parser,\
javax.swing.text.rtf,\
javax.swing.tree,\
javax.swing.undo,\
javax.security.cert,\
javax.xml.parsers,\
javax.xml.bind,\
javax.net.ssl,\
org.w3c.dom,\
org.w3c.dom.bootstrap,\
org.w3c.dom.events,\
org.w3c.dom.ls,\
org.xml.sax.ext,\
org.xml.sax.helpers,\
org.xml.sax,\
javax.sql,\
javax.net,\
javax.xml.datatype,\
javax.xml.namespace,\
javax.xml.stream,\
javax.xml.transform,\
javax.xml.transform.dom,\
javax.xml.transform.stax,\
javax.xml.transform.sax,\
javax.xml.transform.stream,\
javax.xml.validation,\
javax.naming,\
javax.naming.spi,\
javax.naming.ldap,\
javax.security.auth.callback,\
javax.security.auth.x500,\
javax.accessibility,\
sun.swing,\
sun.misc,\
org.jdom,\
org.jdom.input,\
org.jdom.output,\
org.slf4j,\
com.jcraft.jsch,\
net.sf.expectit,\
net.sf.expectit.matcher,\
org.apache.commons.csv,\
com.profesorfalken.jpowershell,\
com.sun.javafx,\
javafx.collections,\
javafx.application,\
javax.swing,\
javafx.embed.swing,\
javafx.event,\
javafx.scene,\
javafx.scene.chart,\
javafx.scene.control,\
javafx.scene.input

osgi.bundles=\
reference:file:../../bundles/org.eclipse.osgi.services-3.5.100@2:start,\
reference:file:../../bundles/org.eclipse.equinox.ds-1.4.400.jar@2:start,\
reference:file:../../bundles/org.eclipse.equinox.util-1.0.500.jar@2:start,\
reference:file:../../bundles/org.eclipse.equinox.console-1.1.200.jar@2:start,\
reference:file:../../bundles/org.eclipse.equinox.console.ssh-1.0.100.jar@2:start,\
reference:file:../../bundles/org.eclipse.equinox.console.jaas.fragment-1.0.0.jar,\
reference:file:../../bundles/mina-core-2.0.7.jar@2:start,\
reference:file:../../bundles/sshd-core-0.14.0.jar@2:start,\
reference:file:../../bundles/mail-1.4.3.jar@2:start,\
reference:file:../../bundles/mariadb-java-client-3.0.11.1-mms.jar@2:start,\
reference:file:../../bundles/xz-1.8@2:start,\
reference:file:../../bundles/commons-compress-1.20@2:start,\
reference:file:../../bundles/commons-net-3.2@2:start,\
reference:file:../../bundles/slf4j-api-1.7.25@2:start,\
reference:file:../../bundles/jackson-core-2.11.4.jar@2:start,\
reference:file:../../bundles/jackson-annotations-2.11.4.jar@2:start,\
reference:file:../../bundles/jackson-databind-2.11.4.jar@2:start,\
reference:file:../../bundles/logback-core-1.2.3.jar@2:start,\
reference:file:../../bundles/logback-classic-1.2.3.jar@2:start,\
reference:file:../../bundles/org.apache.felix.configadmin-1.8.14.jar@2:start,\
reference:file:../../bundles/org.apache.felix.gogo.command-0.10.0.jar@2:start,\
reference:file:../../bundles/org.apache.felix.gogo.runtime-0.10.0.jar@2:start,\
reference:file:../../bundles/org.apache.felix.gogo.shell-0.10.0.jar@2:start,\
reference:file:../../bundles/mms-extension-logback-1.7.0-076.jar,\
reference:file:../../bundles/omslibrary-1.0.0.47-rev9.jar@3:start,\
reference:file:../../bundles/mms-framework-core-1.7.0-076.jar@6:start,\
reference:file:../../bundles/mms-framework-app-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-tool-jmx-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-framework-gui-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-framework-geometry-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-framework-app-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-driver-dgh-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-driver-can-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-driver-gps-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-adapter-dispatch-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-frontrunner-canvas-3.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-frontrunner-common-3.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-frontrunner-database-3.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-tool-i18n-1.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-frontrunner-central-3.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-frontrunner-desktop-3.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-frontrunner-server-remote-3.7.0-076.jar@3:start,\
reference:file:../../bundles/mms-frontrunner-embedded-remote-3.7.0-076.jar@3:start,\
reference:file:../../bundles/com.diffplug.osgi.extension.sun.misc-0.0.0.jar,\
reference:file:../../bundles/org.apache.servicemix.bundles.snmp4j-2.2.2_1.jar@3:start,\
reference:file:../../bundles/fcpcommon-1.2.0.22-AHS-15.jar@3:start,\
reference:file:../../bundles/fcpclient-1.2.0.22-AHS-15.jar@3:start,\
reference:file:../../bundles/guava-27.0.1-jre.jar,\
reference:file:../../bundles/failureaccess-1.0.1.jar,\
reference:file:../../bundles/protobuf-java-3.21.5.jar,\
reference:file:../../bundles/commons-math3-3.6.jar,\
reference:file:../../bundles/commons-csv-1.9.0.jar,\

#we should avoid having the embedded-remote at controller's side, but
#the way the operator log window is designed, it depends on playbackmessage which is a wrapper of other things
#including embedded remote api requests. later if playbackmessage serializes just a string representation as oppose of
#the entire object(request), we can get rid of the embedded-remote api here...
# this problem doesn't have on eclipse because eclipse loads all classes in the same class loader, diferent from osgi
osgi.bundles.defaultStartLevel=4
#osgi.debug=file:../conf/.options
